# Generated by Django 5.2.4 on 2025-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=600, unique=True)),
                ('published_year', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
            ],
        ),
    ]
