# Generated by Django 5.2.4 on 2025-10-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Biography', 'Biography'), ('Children', 'Children'), ('Coding', 'Coding')], max_length=50),
        ),
    ]
