# Generated by Django 5.2.4 on 2025-10-03 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('lib_card_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
